### ISSUE TITLE
Android Transaction complete callback

### ISSUE THREAD

**Issue by spycedev** [ProteanSoftware/capacitor-square#4]
Hello again,

The square app is properly opening on any device I've tried now 👍 
Transactions are approving and showing in the dashboard 👍 

However, the callback on android doesn't appear to work. 
As soon as we click "New Sale" the app crashes completely.
There's not enough time for the event listener to see anything.
Also tried on multiple emulators and real devices

I've added the package name and SHA-1 debug fingerprint to the square dashboard (although I think that's more meant for allowing transactions compared to allowing callbacks?)

Any suggestions?

![image](https://user-images.githubusercontent.com/83834054/170601399-dbcd6c8e-1601-410f-84b4-48bff31a791b.png)

**Comment by AshleyMedway** [comment]
Is there any error visible in the logcat?

**Comment by spycedev** [comment]
Okay, this should help

2022-05-27 13:41:20.907 18967-18967/? I/libc: SetHeapTaggingLevel: tag level set to 0
2022-05-27 13:41:20.915 18967-18967/? I/m.spyce.courie: Late-enabling -Xcheck:jni
2022-05-27 13:41:20.933 18967-18967/? E/USNET: USNET: appName: com.spyce.courier
2022-05-27 13:41:20.934 18967-18967/? D/ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
2022-05-27 13:41:20.936 18967-18967/? D/ActivityThread: setConscryptValidator
2022-05-27 13:41:20.936 18967-18967/? D/ActivityThread: setConscryptValidator - put
2022-05-27 13:41:20.954 18967-18967/com.spyce.courier D/ActivityThread: handleBindApplication()++ app=com.spyce.courier
2022-05-27 13:41:20.955 18967-18967/com.spyce.courier D/CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10511; state: DISABLED
2022-05-27 13:41:20.962 18967-18967/com.spyce.courier D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
2022-05-27 13:41:20.998 18967-18967/com.spyce.courier D/LoadedApk: LoadedApk::makeApplication() appContext.mOpPackageName=com.spyce.courier appContext.mBasePackageName=com.spyce.courier
2022-05-27 13:41:20.999 18967-18967/com.spyce.courier D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2022-05-27 13:41:21.012 18967-18967/com.spyce.courier D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2022-05-27 13:41:21.018 18967-18967/com.spyce.courier D/ActivityThread: handleBindApplication() --
2022-05-27 13:41:21.034 18967-19000/com.spyce.courier D/OpenGLRenderer: RenderThread::requireGlContext()
2022-05-27 13:41:21.035 18967-19000/com.spyce.courier I/AdrenoGLES-0: QUALCOMM build                   : 193b2ee, I593c16c433
    Build Date                       : 10/07/21
    OpenGL ES Shader Compiler Version: EV031.32.02.10
    Local Branch                     : Test-lib-SR05432264
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2022-05-27 13:41:21.035 18967-19000/com.spyce.courier I/AdrenoGLES-0: Build Config                     : S P 10.0.5 AArch64
2022-05-27 13:41:21.035 18967-19000/com.spyce.courier I/AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
2022-05-27 13:41:21.045 18967-19000/com.spyce.courier I/AdrenoGLES-0: PFP: 0x016dd093, ME: 0x00000000
2022-05-27 13:41:21.059 18967-19000/com.spyce.courier D/OpenGLRenderer: RenderThread::setGrContext()
2022-05-27 13:41:21.077 18967-18967/com.spyce.courier E/m.spyce.courie: Invalid ID 0x00000000.
2022-05-27 13:41:21.091 18967-18967/com.spyce.courier I/DecorView: [INFO] isPopOver=false, config=true
2022-05-27 13:41:21.091 18967-18967/com.spyce.courier I/DecorView: updateCaptionType >> DecorView@5d6ede4[], isFloating=false, isApplication=true, hasWindowControllerCallback=true, hasWindowDecorCaption=false
2022-05-27 13:41:21.091 18967-18967/com.spyce.courier D/DecorView: setCaptionType = 0, this = DecorView@5d6ede4[]
2022-05-27 13:41:21.099 18967-18967/com.spyce.courier I/DecorView: getCurrentDensityDpi: from real metrics. densityDpi=420 msg=resources_loaded
2022-05-27 13:41:21.104 18967-18967/com.spyce.courier W/m.spyce.courie: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
2022-05-27 13:41:21.105 18967-18967/com.spyce.courier W/m.spyce.courie: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
2022-05-27 13:41:21.120 18967-18967/com.spyce.courier I/WebViewFactory: Loading com.google.android.webview version 101.0.4951.61 (code 495106134)
2022-05-27 13:41:21.133 18967-18967/com.spyce.courier W/m.spyce.courie: Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (unsupported, reflection, allowed)
2022-05-27 13:41:21.133 18967-18967/com.spyce.courier W/m.spyce.courie: Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (unsupported, reflection, allowed)
2022-05-27 13:41:21.133 18967-18967/com.spyce.courier W/m.spyce.courie: Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (unsupported, reflection, allowed)
2022-05-27 13:41:21.133 18967-18967/com.spyce.courier W/m.spyce.courie: Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (unsupported, reflection, allowed)
2022-05-27 13:41:21.133 18967-18967/com.spyce.courier W/m.spyce.courie: Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (unsupported, reflection, allowed)
2022-05-27 13:41:21.135 18967-18967/com.spyce.courier I/cr_WVCFactoryProvider: Loaded version=101.0.4951.61 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
2022-05-27 13:41:21.147 18967-18967/com.spyce.courier E/m.spyce.courie: Invalid ID 0x00000000.
2022-05-27 13:41:21.147 18967-18967/com.spyce.courier E/m.spyce.courie: Invalid ID 0x00000000.
2022-05-27 13:41:21.150 18967-18967/com.spyce.courier I/cr_LibraryLoader: Successfully loaded native library
2022-05-27 13:41:21.151 18967-18967/com.spyce.courier I/cr_CachingUmaRecorder: Flushed 9 samples from 9 histograms.
2022-05-27 13:41:21.190 18967-19020/com.spyce.courier W/chromium: [WARNING:dns_config_service_android.cc(115)] Failed to read DnsConfig.
2022-05-27 13:41:21.212 18967-18967/com.spyce.courier D/CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10511; state: ENABLED
2022-05-27 13:41:21.232 18967-18967/com.spyce.courier D/Capacitor: Starting BridgeActivity
2022-05-27 13:41:21.240 18967-18967/com.spyce.courier D/Capacitor: Registering plugin: WebView
2022-05-27 13:41:21.241 18967-18967/com.spyce.courier D/Capacitor: Registering plugin: CapacitorSquare
2022-05-27 13:41:21.248 18967-18967/com.spyce.courier E/Capacitor: Unable to read file at path public/plugins
2022-05-27 13:41:21.248 18967-18967/com.spyce.courier D/Capacitor: Loading app at http://localhost
2022-05-27 13:41:21.254 18967-19034/com.spyce.courier W/m.spyce.courie: Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (unsupported, reflection, allowed)
2022-05-27 13:41:21.260 18967-18967/com.spyce.courier D/Capacitor: App started
2022-05-27 13:41:21.261 18967-19034/com.spyce.courier W/cr_media: Requires BLUETOOTH permission
2022-05-27 13:41:21.262 18967-18967/com.spyce.courier D/Capacitor: App resumed
2022-05-27 13:41:21.267 18967-19000/com.spyce.courier D/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
2022-05-27 13:41:21.276 18967-18967/com.spyce.courier I/ViewRootImpl@3c41488[MainActivity]: setView = com.android.internal.policy.DecorView@5d6ede4 TM=true
2022-05-27 13:41:21.280 18967-19020/com.spyce.courier E/chromium: [ERROR:simple_index_file_posix.cc(36)] opendir /data/user/0/com.spyce.courier/cache/WebView/Default/HTTP Cache/Code Cache/wasm: No such file or directory (2)
2022-05-27 13:41:21.280 18967-19020/com.spyce.courier E/chromium: [ERROR:simple_index_file.cc(577)] Could not reconstruct index from disk
2022-05-27 13:41:21.280 18967-19035/com.spyce.courier E/chromium: [ERROR:simple_index_file_posix.cc(36)] opendir /data/user/0/com.spyce.courier/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
2022-05-27 13:41:21.280 18967-19035/com.spyce.courier E/chromium: [ERROR:simple_index_file.cc(577)] Could not reconstruct index from disk
2022-05-27 13:41:21.296 18967-19036/com.spyce.courier D/Capacitor: Handling local request: http://localhost/
2022-05-27 13:41:21.324 18967-18967/com.spyce.courier I/ViewRootImpl@3c41488[MainActivity]: Relayout returned: old=(0,0,1080,2316) new=(0,0,1080,2316) req=(1080,2316)0 dur=8 res=0x7 s={true 480509473968} ch=true fn=-1
2022-05-27 13:41:21.326 18967-19000/com.spyce.courier D/hw-ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
2022-05-27 13:41:21.326 18967-18967/com.spyce.courier I/ViewRootImpl@3c41488[MainActivity]: [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11374 android.view.ViewRootImpl.performTraversals:4167 android.view.ViewRootImpl.doTraversal:2893 
2022-05-27 13:41:21.326 18967-19000/com.spyce.courier D/OpenGLRenderer: eglCreateWindowSurface
2022-05-27 13:41:21.348 18967-19000/com.spyce.courier I/BufferQueueProducer: [ViewRootImpl@3c41488[MainActivity]#0(BLAST Consumer)0](id:4a1700000000,api:1,p:18967,c:18967) queueBuffer: queued for the first time.
2022-05-27 13:41:21.349 18967-19000/com.spyce.courier D/OpenGLRenderer: GPIS:: SetUp Pid : 18967    Tid : 19000
2022-05-27 13:41:21.354 18967-18967/com.spyce.courier I/ViewRootImpl@3c41488[MainActivity]: [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4969 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
2022-05-27 13:41:21.355 18967-18967/com.spyce.courier I/ViewRootImpl@3c41488[MainActivity]: [DP] rdf()
2022-05-27 13:41:21.355 18967-18967/com.spyce.courier D/ViewRootImpl@3c41488[MainActivity]: reportDrawFinished (fn: -1) 
2022-05-27 13:41:21.377 18967-18967/com.spyce.courier I/ViewRootImpl@3c41488[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1 1
2022-05-27 13:41:21.380 18967-18967/com.spyce.courier D/InputMethodManager: startInputInner - Id : 0
2022-05-27 13:41:21.380 18967-18967/com.spyce.courier I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2022-05-27 13:41:21.387 18967-19036/com.spyce.courier D/Capacitor: Handling local request: http://localhost/src/index.js
2022-05-27 13:41:21.389 18967-19017/com.spyce.courier D/Capacitor: Handling local request: http://localhost/cordova.js
2022-05-27 13:41:21.390 18967-19020/com.spyce.courier D/Capacitor: Handling local request: http://localhost/static/css/main.5af9422d.css
2022-05-27 13:41:21.393 18967-19071/com.spyce.courier D/Capacitor: Handling local request: http://localhost/static/js/main.4a7d1870.js
2022-05-27 13:41:21.398 18967-18967/com.spyce.courier D/InputMethodManager: startInputInner - Id : 0
2022-05-27 13:41:21.406 18967-19036/com.spyce.courier E/Capacitor: Unable to open asset URL: http://localhost/src/index.js
2022-05-27 13:41:21.411 18967-19036/com.spyce.courier E/Capacitor: Unable to open asset URL: http://localhost/src/index.js
2022-05-27 13:41:21.434 18967-19036/com.spyce.courier E/Capacitor: Unable to open asset URL: http://localhost/src/index.js
2022-05-27 13:41:21.578 18967-19071/com.spyce.courier D/Capacitor: Handling local request: http://localhost/static/media/spyce_icon.7a9d97728bcc5b3dc31b.png
2022-05-27 13:41:21.640 18967-18967/com.spyce.courier I/Capacitor/Console: File: http://localhost/static/js/main.4a7d1870.js - Line 2 - Msg: working
2022-05-27 13:41:21.657 18967-19071/com.spyce.courier D/Capacitor: Handling local request: http://localhost/src/favicon.svg
2022-05-27 13:41:21.657 18967-19071/com.spyce.courier E/Capacitor: Unable to open asset URL: http://localhost/src/favicon.svg
2022-05-27 13:41:21.658 18967-19071/com.spyce.courier E/Capacitor: Unable to open asset URL: http://localhost/src/favicon.svg
2022-05-27 13:41:21.660 18967-19071/com.spyce.courier E/Capacitor: Unable to open asset URL: http://localhost/src/favicon.svg
2022-05-27 13:41:22.006 18967-18967/com.spyce.courier I/Capacitor/Console: File: http://localhost/static/js/main.4a7d1870.js - Line 2 - Msg: false
2022-05-27 13:42:12.288 18967-18967/com.spyce.courier I/ViewRootImpl@3c41488[MainActivity]: ViewPostIme pointer 0
2022-05-27 13:42:12.325 18967-18967/com.spyce.courier I/ViewRootImpl@3c41488[MainActivity]: ViewPostIme pointer 1
2022-05-27 13:42:12.334 18967-18967/com.spyce.courier I/IMM_LC: hsifw() - flags=0, caller=android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow:1846 org.chromium.content.browser.input.ImeAdapterImpl.i:174 org.chromium.content.browser.input.ImeAdapterImpl.updateState:525 android.os.MessageQueue.nativePollOnce:-2 android.os.MessageQueue.next:335 
2022-05-27 13:42:12.334 18967-18967/com.spyce.courier I/IMM_LC: hideSoftInputFromWindow - mService.hideSoftInput
2022-05-27 13:42:12.354 18967-18967/com.spyce.courier D/Capacitor: App paused
2022-05-27 13:42:12.378 18967-18967/com.spyce.courier I/ViewRootImpl@3c41488[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1
2022-05-27 13:42:12.675 18967-18967/com.spyce.courier I/ViewRootImpl@3c41488[MainActivity]: handleAppVisibility mAppVisible=true visible=false
2022-05-27 13:42:12.682 18967-19000/com.spyce.courier D/OpenGLRenderer: setSurface called with nullptr
2022-05-27 13:42:12.682 18967-19000/com.spyce.courier D/OpenGLRenderer: setSurface() destroyed EGLSurface
2022-05-27 13:42:12.682 18967-19000/com.spyce.courier D/OpenGLRenderer: destroyEglSurface
2022-05-27 13:42:12.688 18967-18967/com.spyce.courier I/ViewRootImpl@3c41488[MainActivity]: Relayout returned: old=(0,0,1080,2316) new=(0,0,1080,2316) req=(1080,2316)8 dur=4 res=0x5 s={false 0} ch=true fn=62
2022-05-27 13:42:12.771 18967-18967/com.spyce.courier D/InputTransport: Input channel destroyed: 'ClientS', fd=192
2022-05-27 13:42:12.817 18967-18967/com.spyce.courier I/ViewRootImpl@3c41488[MainActivity]: stopped(true) old=false
2022-05-27 13:42:12.821 18967-18967/com.spyce.courier D/Capacitor: App stopped
2022-05-27 13:42:12.821 18967-18967/com.spyce.courier D/Capacitor: Saving instance state!
2022-05-27 13:42:12.841 18967-18967/com.spyce.courier I/ViewRootImpl@3c41488[MainActivity]: Relayout returned: old=(0,0,1080,2316) new=(0,0,1080,2316) req=(1080,2316)8 dur=6 res=0x5 s={false 0} ch=false fn=-1
2022-05-27 13:42:23.451 18967-18967/com.spyce.courier I/ViewRootImpl@3c41488[MainActivity]: handleAppVisibility mAppVisible=false visible=true
2022-05-27 13:42:23.460 18967-19000/com.spyce.courier D/OpenGLRenderer: setSurface called with nullptr
2022-05-27 13:42:23.467 18967-18967/com.spyce.courier I/ViewRootImpl@3c41488[MainActivity]: Relayout returned: old=(0,0,1080,2316) new=(0,0,1080,2316) req=(1080,2316)4 dur=4 res=0x1 s={false 0} ch=false fn=-1
2022-05-27 13:42:23.468 18967-18967/com.spyce.courier D/Capacitor: Unable to find a Capacitor plugin to handle requestCode, trying Cordova plugins 1416014193
2022-05-27 13:42:23.469 18967-18967/com.spyce.courier I/ViewRootImpl@3c41488[MainActivity]: stopped(false) old=true
2022-05-27 13:42:23.470 18967-18967/com.spyce.courier D/Capacitor: App restarted
2022-05-27 13:42:23.472 18967-18967/com.spyce.courier D/Capacitor: App started
2022-05-27 13:42:23.474 18967-18967/com.spyce.courier D/AndroidRuntime: Shutting down VM
2022-05-27 13:42:23.475 18967-18967/com.spyce.courier E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.spyce.courier, PID: 18967
    java.lang.IllegalArgumentException: method com.proteansoftware.capacitor.square.CapacitorSquarePlugin.chargeRequest argument 1 has type int, got com.getcapacitor.PluginCall
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.Plugin.triggerActivityCallback(Plugin.java:155)
        at com.getcapacitor.Plugin.lambda$initializeActivityLaunchers$0$Plugin(Plugin.java:117)
        at com.getcapacitor.-$$Lambda$Plugin$9tit0PZrRMA5UA4Z_xqI4yDk4JY.onActivityResult(Unknown Source:6)
        at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
        at androidx.lifecycle.ReportFragment$LifecycleCallbacks.onActivityPostStarted(ReportFragment.java:187)
        at android.app.Activity.dispatchActivityPostStarted(Activity.java:1420)
        at android.app.Activity.performStart(Activity.java:8352)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4060)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8663)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
![image](https://user-images.githubusercontent.com/83834054/170787246-e8c5deb3-0a85-4ecc-9d8c-f8151ce873ff.png)

**Comment by AshleyMedway** [comment]
The screenshot is perfect leave that with me :)

**Comment by spycedev** [comment]
Right on! We thank you very much for your help. 
I tried to look at the plugin code but I know 0 Java so i have no idea where to start :)
This plugin will help our business a lot, thanks again!

**Comment by AshleyMedway** [comment]
Can you confirm the version of capacitor installed in your package.json

**Comment by spycedev** [comment]
"@capacitor/android": "^3.5.1",
    "@capacitor/core": "^3.5.1",

**Comment by AshleyMedway** [comment]
Can you try with version 3.2.8. I've not been able to test it in our app yet but I think it should work

```bash
npm i @proteansoftware/capacitor-square@3.2.8
```

**Comment by spycedev** [comment]
Thank you very much! No crash! 

![image](https://user-images.githubusercontent.com/83834054/170803451-143e2e81-2ed8-4654-853f-d55616884bf2.png)

**Comment by AshleyMedway** [comment]
No problem, enjoy working with capacitor :)
